### PR TITLE
add development instructions

### LINKED ISSUE #2: can't find libxml on build
image

### PR DESCRIPTION
**Pull request by afeld**
Fixes #2.

/cc https://github.com/moovweb/gokogiri/pull/95

### CODE REVIEW

**Comment by jcscottiii** [comment]
This project uses the `vendor` folder only supported by Go1.6+ by default (1.5 if you use some env variables). But let's just support 1.6

Your README needs to tell people to use 1.6

**Comment by afeld** [comment]
I happen to be using the `vendor/` folder, but it would still work in older versions of Go with the old dependency structure, right?

**Comment by jcscottiii** [comment]
it would work if the person with Go version <1.6 runs `go get` personally on their computer. But otherwise, all the old toolchains only look in certain places for dependencies. Go1.6 adds the vendor folder for a new location.

**Comment by afeld** [comment]
D'oh, I get it now. Forgot that we were checking the dependencies into the repository. Updated!

**Pull request merged**
